apiVersion: apps/v1
kind: Deployment
metadata:
  name: wedding
  labels:
    app.kubernetes.io/name: wedding
    app.kubernetes.io/instance: wedding
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wedding
      app.kubernetes.io/instance: wedding
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wedding
        app.kubernetes.io/instance: wedding
    spec:
      securityContext:
        fsGroup: 2000
      containers:
        - name: wedding
          args:
            - "node"
            - "build"
          securityContext:
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          image: "dannylongeuay/ndsq-wedding:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 128Mi
