apiVersion: v1
kind: Service
metadata:
  name: wedding
  labels:
    app.kubernetes.io/name: wedding
    app.kubernetes.io/instance: wedding
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: wedding
    app.kubernetes.io/instance: wedding
